/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as ProfileImport } from './routes/profile'
import { Route as IndexImport } from './routes/index'
import { Route as CommunitiesIndexImport } from './routes/communities/index'
import { Route as EventsSubmitImport } from './routes/events/submit'
import { Route as EventsEventIdImport } from './routes/events/$eventId'
import { Route as CommunitiesCommunityIdImport } from './routes/communities/$communityId'
import { Route as CommunitiesManagementIndexImport } from './routes/communities/management/index'
import { Route as CommunitiesManagementCreateImport } from './routes/communities/management/create'
import { Route as CommunitiesManagementCommunityIdImport } from './routes/communities/management/$communityId'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CommunitiesIndexRoute = CommunitiesIndexImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRoute,
} as any)

const EventsSubmitRoute = EventsSubmitImport.update({
  id: '/events/submit',
  path: '/events/submit',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

const CommunitiesCommunityIdRoute = CommunitiesCommunityIdImport.update({
  id: '/communities/$communityId',
  path: '/communities/$communityId',
  getParentRoute: () => rootRoute,
} as any)

const CommunitiesManagementIndexRoute = CommunitiesManagementIndexImport.update(
  {
    id: '/communities/management/',
    path: '/communities/management/',
    getParentRoute: () => rootRoute,
  } as any,
)

const CommunitiesManagementCreateRoute =
  CommunitiesManagementCreateImport.update({
    id: '/communities/management/create',
    path: '/communities/management/create',
    getParentRoute: () => rootRoute,
  } as any)

const CommunitiesManagementCommunityIdRoute =
  CommunitiesManagementCommunityIdImport.update({
    id: '/communities/management/$communityId',
    path: '/communities/management/$communityId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/communities/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof rootRoute
    }
    '/events/submit': {
      id: '/events/submit'
      path: '/events/submit'
      fullPath: '/events/submit'
      preLoaderRoute: typeof EventsSubmitImport
      parentRoute: typeof rootRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesIndexImport
      parentRoute: typeof rootRoute
    }
    '/communities/management/$communityId': {
      id: '/communities/management/$communityId'
      path: '/communities/management/$communityId'
      fullPath: '/communities/management/$communityId'
      preLoaderRoute: typeof CommunitiesManagementCommunityIdImport
      parentRoute: typeof rootRoute
    }
    '/communities/management/create': {
      id: '/communities/management/create'
      path: '/communities/management/create'
      fullPath: '/communities/management/create'
      preLoaderRoute: typeof CommunitiesManagementCreateImport
      parentRoute: typeof rootRoute
    }
    '/communities/management/': {
      id: '/communities/management/'
      path: '/communities/management'
      fullPath: '/communities/management'
      preLoaderRoute: typeof CommunitiesManagementIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities': typeof CommunitiesIndexRoute
  '/communities/management/$communityId': typeof CommunitiesManagementCommunityIdRoute
  '/communities/management/create': typeof CommunitiesManagementCreateRoute
  '/communities/management': typeof CommunitiesManagementIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities': typeof CommunitiesIndexRoute
  '/communities/management/$communityId': typeof CommunitiesManagementCommunityIdRoute
  '/communities/management/create': typeof CommunitiesManagementCreateRoute
  '/communities/management': typeof CommunitiesManagementIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/submit': typeof EventsSubmitRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/communities/management/$communityId': typeof CommunitiesManagementCommunityIdRoute
  '/communities/management/create': typeof CommunitiesManagementCreateRoute
  '/communities/management/': typeof CommunitiesManagementIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/communities/$communityId'
    | '/events/$eventId'
    | '/events/submit'
    | '/communities'
    | '/communities/management/$communityId'
    | '/communities/management/create'
    | '/communities/management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/communities/$communityId'
    | '/events/$eventId'
    | '/events/submit'
    | '/communities'
    | '/communities/management/$communityId'
    | '/communities/management/create'
    | '/communities/management'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/communities/$communityId'
    | '/events/$eventId'
    | '/events/submit'
    | '/communities/'
    | '/communities/management/$communityId'
    | '/communities/management/create'
    | '/communities/management/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsSubmitRoute: typeof EventsSubmitRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  CommunitiesManagementCommunityIdRoute: typeof CommunitiesManagementCommunityIdRoute
  CommunitiesManagementCreateRoute: typeof CommunitiesManagementCreateRoute
  CommunitiesManagementIndexRoute: typeof CommunitiesManagementIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsSubmitRoute: EventsSubmitRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  CommunitiesManagementCommunityIdRoute: CommunitiesManagementCommunityIdRoute,
  CommunitiesManagementCreateRoute: CommunitiesManagementCreateRoute,
  CommunitiesManagementIndexRoute: CommunitiesManagementIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/sign-in",
        "/sign-up",
        "/communities/$communityId",
        "/events/$eventId",
        "/events/submit",
        "/communities/",
        "/communities/management/$communityId",
        "/communities/management/create",
        "/communities/management/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/communities/$communityId": {
      "filePath": "communities/$communityId.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    },
    "/events/submit": {
      "filePath": "events/submit.tsx"
    },
    "/communities/": {
      "filePath": "communities/index.tsx"
    },
    "/communities/management/$communityId": {
      "filePath": "communities/management/$communityId.tsx"
    },
    "/communities/management/create": {
      "filePath": "communities/management/create.tsx"
    },
    "/communities/management/": {
      "filePath": "communities/management/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
