/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FileConventionsRouteRouteImport } from './routes/file-conventions/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FileConventionsIndexRouteImport } from './routes/file-conventions/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities/index'
import { Route as FileConventionsEventSlugRouteImport } from './routes/file-conventions/$eventSlug'
import { Route as EventsSubmitRouteImport } from './routes/events/submit'
import { Route as EventsEventSlugRouteImport } from './routes/events/$eventSlug'
import { Route as DemoStreamingRouteImport } from './routes/demo/streaming'
import { Route as DemoSsrRouteImport } from './routes/demo/ssr'
import { Route as DemoSearchRouteImport } from './routes/demo/search'
import { Route as DemoRscQueryRouteImport } from './routes/demo/rsc-query'
import { Route as DemoLoadersRouteImport } from './routes/demo/loaders'
import { Route as CommunitiesCreateRouteImport } from './routes/communities/create'
import { Route as CommunitiesCommunitySlugRouteImport } from './routes/communities/$communitySlug'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as FileConventionsLayoutRouteRouteImport } from './routes/file-conventions/_layout/route'
import { Route as DemoauthenticatedRouteRouteImport } from './routes/demo/(authenticated)/route'
import { Route as EventsProSubmitRouteImport } from './routes/events/pro.submit'
import { Route as EventsProEventIdRouteImport } from './routes/events/pro.$eventId'
import { Route as DemoRscIdRouteImport } from './routes/demo/rsc.$id'
import { Route as DemoauthenticatedSettingsRouteImport } from './routes/demo/(authenticated)/settings'
import { Route as DemoauthenticatedDashboardRouteImport } from './routes/demo/(authenticated)/dashboard'
import { Route as ApiDemoNameRouteImport } from './routes/api/demo.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as FileConventionsOneTwoThreeRouteImport } from './routes/file-conventions/one.two.three'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FileConventionsRouteRoute = FileConventionsRouteRouteImport.update({
  id: '/file-conventions',
  path: '/file-conventions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileConventionsIndexRoute = FileConventionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FileConventionsRouteRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const FileConventionsEventSlugRoute =
  FileConventionsEventSlugRouteImport.update({
    id: '/$eventSlug',
    path: '/$eventSlug',
    getParentRoute: () => FileConventionsRouteRoute,
  } as any)
const EventsSubmitRoute = EventsSubmitRouteImport.update({
  id: '/events/submit',
  path: '/events/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventSlugRoute = EventsEventSlugRouteImport.update({
  id: '/events/$eventSlug',
  path: '/events/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStreamingRoute = DemoStreamingRouteImport.update({
  id: '/demo/streaming',
  path: '/demo/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSsrRoute = DemoSsrRouteImport.update({
  id: '/demo/ssr',
  path: '/demo/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSearchRoute = DemoSearchRouteImport.update({
  id: '/demo/search',
  path: '/demo/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRscQueryRoute = DemoRscQueryRouteImport.update({
  id: '/demo/rsc-query',
  path: '/demo/rsc-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLoadersRoute = DemoLoadersRouteImport.update({
  id: '/demo/loaders',
  path: '/demo/loaders',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCreateRoute = CommunitiesCreateRouteImport.update({
  id: '/communities/create',
  path: '/communities/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunitySlugRoute =
  CommunitiesCommunitySlugRouteImport.update({
    id: '/communities/$communitySlug',
    path: '/communities/$communitySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const FileConventionsLayoutRouteRoute =
  FileConventionsLayoutRouteRouteImport.update({
    id: '/_layout',
    getParentRoute: () => FileConventionsRouteRoute,
  } as any)
const DemoauthenticatedRouteRoute = DemoauthenticatedRouteRouteImport.update({
  id: '/demo/(authenticated)',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsProSubmitRoute = EventsProSubmitRouteImport.update({
  id: '/events/pro/submit',
  path: '/events/pro/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsProEventIdRoute = EventsProEventIdRouteImport.update({
  id: '/events/pro/$eventId',
  path: '/events/pro/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRscIdRoute = DemoRscIdRouteImport.update({
  id: '/demo/rsc/$id',
  path: '/demo/rsc/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoauthenticatedSettingsRoute =
  DemoauthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DemoauthenticatedRouteRoute,
  } as any)
const DemoauthenticatedDashboardRoute =
  DemoauthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => DemoauthenticatedRouteRoute,
  } as any)
const ApiDemoNameRoute = ApiDemoNameRouteImport.update({
  id: '/api/demo/$name',
  path: '/api/demo/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FileConventionsOneTwoThreeRoute =
  FileConventionsOneTwoThreeRouteImport.update({
    id: '/one/two/three',
    path: '/one/two/three',
    getParentRoute: () => FileConventionsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file-conventions': typeof FileConventionsLayoutRouteRoute
  '/calendar': typeof CalendarRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo': typeof DemoauthenticatedRouteRouteWithChildren
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/api/mcp': typeof ApiMcpRoute
  '/communities/$communitySlug': typeof CommunitiesCommunitySlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/demo/loaders': typeof DemoLoadersRoute
  '/demo/rsc-query': typeof DemoRscQueryRoute
  '/demo/search': typeof DemoSearchRoute
  '/demo/ssr': typeof DemoSsrRoute
  '/demo/streaming': typeof DemoStreamingRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/file-conventions/$eventSlug': typeof FileConventionsEventSlugRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/file-conventions/': typeof FileConventionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/$name': typeof ApiDemoNameRoute
  '/demo/dashboard': typeof DemoauthenticatedDashboardRoute
  '/demo/settings': typeof DemoauthenticatedSettingsRoute
  '/demo/rsc/$id': typeof DemoRscIdRoute
  '/events/pro/$eventId': typeof EventsProEventIdRoute
  '/events/pro/submit': typeof EventsProSubmitRoute
  '/file-conventions/one/two/three': typeof FileConventionsOneTwoThreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo': typeof DemoauthenticatedRouteRouteWithChildren
  '/file-conventions': typeof FileConventionsIndexRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/api/mcp': typeof ApiMcpRoute
  '/communities/$communitySlug': typeof CommunitiesCommunitySlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/demo/loaders': typeof DemoLoadersRoute
  '/demo/rsc-query': typeof DemoRscQueryRoute
  '/demo/search': typeof DemoSearchRoute
  '/demo/ssr': typeof DemoSsrRoute
  '/demo/streaming': typeof DemoStreamingRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/file-conventions/$eventSlug': typeof FileConventionsEventSlugRoute
  '/communities': typeof CommunitiesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/$name': typeof ApiDemoNameRoute
  '/demo/dashboard': typeof DemoauthenticatedDashboardRoute
  '/demo/settings': typeof DemoauthenticatedSettingsRoute
  '/demo/rsc/$id': typeof DemoRscIdRoute
  '/events/pro/$eventId': typeof EventsProEventIdRoute
  '/events/pro/submit': typeof EventsProSubmitRoute
  '/file-conventions/one/two/three': typeof FileConventionsOneTwoThreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file-conventions': typeof FileConventionsRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/my-events': typeof MyEventsRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/demo/(authenticated)': typeof DemoauthenticatedRouteRouteWithChildren
  '/file-conventions/_layout': typeof FileConventionsLayoutRouteRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/api/mcp': typeof ApiMcpRoute
  '/communities/$communitySlug': typeof CommunitiesCommunitySlugRoute
  '/communities/create': typeof CommunitiesCreateRoute
  '/demo/loaders': typeof DemoLoadersRoute
  '/demo/rsc-query': typeof DemoRscQueryRoute
  '/demo/search': typeof DemoSearchRoute
  '/demo/ssr': typeof DemoSsrRoute
  '/demo/streaming': typeof DemoStreamingRoute
  '/events/$eventSlug': typeof EventsEventSlugRoute
  '/events/submit': typeof EventsSubmitRoute
  '/file-conventions/$eventSlug': typeof FileConventionsEventSlugRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/file-conventions/': typeof FileConventionsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/demo/$name': typeof ApiDemoNameRoute
  '/demo/(authenticated)/dashboard': typeof DemoauthenticatedDashboardRoute
  '/demo/(authenticated)/settings': typeof DemoauthenticatedSettingsRoute
  '/demo/rsc/$id': typeof DemoRscIdRoute
  '/events/pro/$eventId': typeof EventsProEventIdRoute
  '/events/pro/submit': typeof EventsProSubmitRoute
  '/file-conventions/one/two/three': typeof FileConventionsOneTwoThreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/file-conventions'
    | '/calendar'
    | '/my-events'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/demo'
    | '/.well-known/openid-configuration'
    | '/api/mcp'
    | '/communities/$communitySlug'
    | '/communities/create'
    | '/demo/loaders'
    | '/demo/rsc-query'
    | '/demo/search'
    | '/demo/ssr'
    | '/demo/streaming'
    | '/events/$eventSlug'
    | '/events/submit'
    | '/file-conventions/$eventSlug'
    | '/communities/'
    | '/file-conventions/'
    | '/api/auth/$'
    | '/api/demo/$name'
    | '/demo/dashboard'
    | '/demo/settings'
    | '/demo/rsc/$id'
    | '/events/pro/$eventId'
    | '/events/pro/submit'
    | '/file-conventions/one/two/three'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/my-events'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/demo'
    | '/file-conventions'
    | '/.well-known/openid-configuration'
    | '/api/mcp'
    | '/communities/$communitySlug'
    | '/communities/create'
    | '/demo/loaders'
    | '/demo/rsc-query'
    | '/demo/search'
    | '/demo/ssr'
    | '/demo/streaming'
    | '/events/$eventSlug'
    | '/events/submit'
    | '/file-conventions/$eventSlug'
    | '/communities'
    | '/api/auth/$'
    | '/api/demo/$name'
    | '/demo/dashboard'
    | '/demo/settings'
    | '/demo/rsc/$id'
    | '/events/pro/$eventId'
    | '/events/pro/submit'
    | '/file-conventions/one/two/three'
  id:
    | '__root__'
    | '/'
    | '/file-conventions'
    | '/calendar'
    | '/my-events'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/demo/(authenticated)'
    | '/file-conventions/_layout'
    | '/.well-known/openid-configuration'
    | '/api/mcp'
    | '/communities/$communitySlug'
    | '/communities/create'
    | '/demo/loaders'
    | '/demo/rsc-query'
    | '/demo/search'
    | '/demo/ssr'
    | '/demo/streaming'
    | '/events/$eventSlug'
    | '/events/submit'
    | '/file-conventions/$eventSlug'
    | '/communities/'
    | '/file-conventions/'
    | '/api/auth/$'
    | '/api/demo/$name'
    | '/demo/(authenticated)/dashboard'
    | '/demo/(authenticated)/settings'
    | '/demo/rsc/$id'
    | '/events/pro/$eventId'
    | '/events/pro/submit'
    | '/file-conventions/one/two/three'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileConventionsRouteRoute: typeof FileConventionsRouteRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  MyEventsRoute: typeof MyEventsRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DemoauthenticatedRouteRoute: typeof DemoauthenticatedRouteRouteWithChildren
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  ApiMcpRoute: typeof ApiMcpRoute
  CommunitiesCommunitySlugRoute: typeof CommunitiesCommunitySlugRoute
  CommunitiesCreateRoute: typeof CommunitiesCreateRoute
  DemoLoadersRoute: typeof DemoLoadersRoute
  DemoRscQueryRoute: typeof DemoRscQueryRoute
  DemoSearchRoute: typeof DemoSearchRoute
  DemoSsrRoute: typeof DemoSsrRoute
  DemoStreamingRoute: typeof DemoStreamingRoute
  EventsEventSlugRoute: typeof EventsEventSlugRoute
  EventsSubmitRoute: typeof EventsSubmitRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDemoNameRoute: typeof ApiDemoNameRoute
  DemoRscIdRoute: typeof DemoRscIdRoute
  EventsProEventIdRoute: typeof EventsProEventIdRoute
  EventsProSubmitRoute: typeof EventsProSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-conventions': {
      id: '/file-conventions'
      path: '/file-conventions'
      fullPath: '/file-conventions'
      preLoaderRoute: typeof FileConventionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-conventions/': {
      id: '/file-conventions/'
      path: '/'
      fullPath: '/file-conventions/'
      preLoaderRoute: typeof FileConventionsIndexRouteImport
      parentRoute: typeof FileConventionsRouteRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-conventions/$eventSlug': {
      id: '/file-conventions/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/file-conventions/$eventSlug'
      preLoaderRoute: typeof FileConventionsEventSlugRouteImport
      parentRoute: typeof FileConventionsRouteRoute
    }
    '/events/submit': {
      id: '/events/submit'
      path: '/events/submit'
      fullPath: '/events/submit'
      preLoaderRoute: typeof EventsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/streaming': {
      id: '/demo/streaming'
      path: '/demo/streaming'
      fullPath: '/demo/streaming'
      preLoaderRoute: typeof DemoStreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/ssr': {
      id: '/demo/ssr'
      path: '/demo/ssr'
      fullPath: '/demo/ssr'
      preLoaderRoute: typeof DemoSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/search': {
      id: '/demo/search'
      path: '/demo/search'
      fullPath: '/demo/search'
      preLoaderRoute: typeof DemoSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rsc-query': {
      id: '/demo/rsc-query'
      path: '/demo/rsc-query'
      fullPath: '/demo/rsc-query'
      preLoaderRoute: typeof DemoRscQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/loaders': {
      id: '/demo/loaders'
      path: '/demo/loaders'
      fullPath: '/demo/loaders'
      preLoaderRoute: typeof DemoLoadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/create': {
      id: '/communities/create'
      path: '/communities/create'
      fullPath: '/communities/create'
      preLoaderRoute: typeof CommunitiesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communitySlug': {
      id: '/communities/$communitySlug'
      path: '/communities/$communitySlug'
      fullPath: '/communities/$communitySlug'
      preLoaderRoute: typeof CommunitiesCommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-conventions/_layout': {
      id: '/file-conventions/_layout'
      path: ''
      fullPath: '/file-conventions'
      preLoaderRoute: typeof FileConventionsLayoutRouteRouteImport
      parentRoute: typeof FileConventionsRouteRoute
    }
    '/demo/(authenticated)': {
      id: '/demo/(authenticated)'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoauthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/pro/submit': {
      id: '/events/pro/submit'
      path: '/events/pro/submit'
      fullPath: '/events/pro/submit'
      preLoaderRoute: typeof EventsProSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/pro/$eventId': {
      id: '/events/pro/$eventId'
      path: '/events/pro/$eventId'
      fullPath: '/events/pro/$eventId'
      preLoaderRoute: typeof EventsProEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/rsc/$id': {
      id: '/demo/rsc/$id'
      path: '/demo/rsc/$id'
      fullPath: '/demo/rsc/$id'
      preLoaderRoute: typeof DemoRscIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/(authenticated)/settings': {
      id: '/demo/(authenticated)/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoauthenticatedSettingsRouteImport
      parentRoute: typeof DemoauthenticatedRouteRoute
    }
    '/demo/(authenticated)/dashboard': {
      id: '/demo/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoauthenticatedDashboardRouteImport
      parentRoute: typeof DemoauthenticatedRouteRoute
    }
    '/api/demo/$name': {
      id: '/api/demo/$name'
      path: '/api/demo/$name'
      fullPath: '/api/demo/$name'
      preLoaderRoute: typeof ApiDemoNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-conventions/one/two/three': {
      id: '/file-conventions/one/two/three'
      path: '/one/two/three'
      fullPath: '/file-conventions/one/two/three'
      preLoaderRoute: typeof FileConventionsOneTwoThreeRouteImport
      parentRoute: typeof FileConventionsRouteRoute
    }
  }
}

interface FileConventionsRouteRouteChildren {
  FileConventionsLayoutRouteRoute: typeof FileConventionsLayoutRouteRoute
  FileConventionsEventSlugRoute: typeof FileConventionsEventSlugRoute
  FileConventionsIndexRoute: typeof FileConventionsIndexRoute
  FileConventionsOneTwoThreeRoute: typeof FileConventionsOneTwoThreeRoute
}

const FileConventionsRouteRouteChildren: FileConventionsRouteRouteChildren = {
  FileConventionsLayoutRouteRoute: FileConventionsLayoutRouteRoute,
  FileConventionsEventSlugRoute: FileConventionsEventSlugRoute,
  FileConventionsIndexRoute: FileConventionsIndexRoute,
  FileConventionsOneTwoThreeRoute: FileConventionsOneTwoThreeRoute,
}

const FileConventionsRouteRouteWithChildren =
  FileConventionsRouteRoute._addFileChildren(FileConventionsRouteRouteChildren)

interface DemoauthenticatedRouteRouteChildren {
  DemoauthenticatedDashboardRoute: typeof DemoauthenticatedDashboardRoute
  DemoauthenticatedSettingsRoute: typeof DemoauthenticatedSettingsRoute
}

const DemoauthenticatedRouteRouteChildren: DemoauthenticatedRouteRouteChildren =
  {
    DemoauthenticatedDashboardRoute: DemoauthenticatedDashboardRoute,
    DemoauthenticatedSettingsRoute: DemoauthenticatedSettingsRoute,
  }

const DemoauthenticatedRouteRouteWithChildren =
  DemoauthenticatedRouteRoute._addFileChildren(
    DemoauthenticatedRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileConventionsRouteRoute: FileConventionsRouteRouteWithChildren,
  CalendarRoute: CalendarRoute,
  MyEventsRoute: MyEventsRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DemoauthenticatedRouteRoute: DemoauthenticatedRouteRouteWithChildren,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  ApiMcpRoute: ApiMcpRoute,
  CommunitiesCommunitySlugRoute: CommunitiesCommunitySlugRoute,
  CommunitiesCreateRoute: CommunitiesCreateRoute,
  DemoLoadersRoute: DemoLoadersRoute,
  DemoRscQueryRoute: DemoRscQueryRoute,
  DemoSearchRoute: DemoSearchRoute,
  DemoSsrRoute: DemoSsrRoute,
  DemoStreamingRoute: DemoStreamingRoute,
  EventsEventSlugRoute: EventsEventSlugRoute,
  EventsSubmitRoute: EventsSubmitRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDemoNameRoute: ApiDemoNameRoute,
  DemoRscIdRoute: DemoRscIdRoute,
  EventsProEventIdRoute: EventsProEventIdRoute,
  EventsProSubmitRoute: EventsProSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
